name: Push DevContainer

on:
  push:

jobs:
  push-devcontainer:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push DevContainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/k-taro56/population-trends-graph-devcontainer
          cacheFrom: ghcr.io/k-taro56/population-trends-graph-devcontainer
          push: always
